# Generated by Django 5.2.7 on 2025-11-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockPricePredictionApp', '0001_initial'),
    ]

    operations = [
    ]
