# Generated by Django 5.2.7 on 2025-11-23 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPricePredictionApp', '0002_auto_20251120_2023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='alert_on_fall',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='alert_on_rise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='alert_threshold_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rise', 'Price Rise'), ('fall', 'Price Fall')], max_length=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('watchlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='StockPricePredictionApp.watchlist')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlertPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('alert_frequency', models.CharField(choices=[('realtime', 'Real-time (Immediate)'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest')], default='realtime', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
