# Generated by Django 5.2.7 on 2025-12-12 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPricePredictionApp', '0004_newsarticle_portfolio_portfolioholding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='sentiment_label',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='portfolioholding',
            name='purchase_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='portfolioholding',
            name='ticker',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ticker',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='alert_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='ticker',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['ticker', '-published_at'], name='StockPriceP_ticker_7a6188_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['sentiment_label', '-published_at'], name='StockPriceP_sentime_a15d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', '-created_at'], name='StockPriceP_user_id_fcbae3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['portfolio', 'ticker'], name='StockPriceP_portfol_52efb2_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['ticker', '-purchase_date'], name='StockPriceP_ticker_1471a4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', '-transaction_date'], name='StockPriceP_portfol_7d0454_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ticker', '-transaction_date'], name='StockPriceP_ticker_2bc703_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'created_at'], name='StockPriceP_user_id_4e57fd_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['ticker', 'alert_enabled'], name='StockPriceP_ticker_855d0c_idx'),
        ),
    ]
